baseURL = "https://tibcosoftware.github.io/flogo/"
languageCode = "en-us"
title = "Project Flogo - Docs and Tutorials"
theme = "hugo-theme-learn"

[params]
  # Author of the site, will be used in meta information
  author = "retgits"
  # Description of the site, will be used in meta information
  description = "Project Flogo - Docs and Tutorials"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = true
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/tibcosoftware/flogo"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-comments'></i> Community"
url = "https://community.tibco.com/products/project-flogo"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-plug'></i> Showcase"
url = "https://tibcosoftware.github.io/flogo/showcases"
weight = 12
